spring:
  profiles:
    active: '@spring.profiles.active@'
server:
  servlet:
    context-path: /mgr
  port: 8080

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.czlt.reproduction.mgr.entity

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

---
spring:
  profiles:
    active: local
  datasource:
    name: test
    url: jdbc:mysql://bjtest.qmcai.com:4009/reproduction
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20